/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AppFeedRouteImport } from './routes/_app/feed'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as GuestRegisterRouteImport } from './routes/_guest/register'
import { Route as AppUNicknameRouteImport } from './routes/_app/u/$nickname'
import { Route as AppUNicknameProjectsProjectIdRouteImport } from './routes/_app/u/$nickname_/projects/$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const GuestRegisterRoute = GuestRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => GuestRoute,
} as any)
const AppUNicknameRoute = AppUNicknameRouteImport.update({
  id: '/u/$nickname',
  path: '/u/$nickname',
  getParentRoute: () => AppRoute,
} as any)
const AppUNicknameProjectsProjectIdRoute =
  AppUNicknameProjectsProjectIdRouteImport.update({
    id: '/u/$nickname_/projects/$projectId',
    path: '/u/$nickname/projects/$projectId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feed': typeof AppFeedRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/u/$nickname': typeof AppUNicknameRoute
  '/u/$nickname/projects/$projectId': typeof AppUNicknameProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feed': typeof AppFeedRoute
  '/login': typeof GuestLoginRoute
  '/register': typeof GuestRegisterRoute
  '/u/$nickname': typeof AppUNicknameRoute
  '/u/$nickname/projects/$projectId': typeof AppUNicknameProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_app/feed': typeof AppFeedRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/register': typeof GuestRegisterRoute
  '/_app/u/$nickname': typeof AppUNicknameRoute
  '/_app/u/$nickname_/projects/$projectId': typeof AppUNicknameProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feed'
    | '/login'
    | '/register'
    | '/u/$nickname'
    | '/u/$nickname/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feed'
    | '/login'
    | '/register'
    | '/u/$nickname'
    | '/u/$nickname/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_guest'
    | '/_app/feed'
    | '/_guest/login'
    | '/_guest/register'
    | '/_app/u/$nickname'
    | '/_app/u/$nickname_/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/feed': {
      id: '/_app/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/register': {
      id: '/_guest/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof GuestRegisterRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_app/u/$nickname': {
      id: '/_app/u/$nickname'
      path: '/u/$nickname'
      fullPath: '/u/$nickname'
      preLoaderRoute: typeof AppUNicknameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/u/$nickname_/projects/$projectId': {
      id: '/_app/u/$nickname_/projects/$projectId'
      path: '/u/$nickname/projects/$projectId'
      fullPath: '/u/$nickname/projects/$projectId'
      preLoaderRoute: typeof AppUNicknameProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFeedRoute: typeof AppFeedRoute
  AppUNicknameRoute: typeof AppUNicknameRoute
  AppUNicknameProjectsProjectIdRoute: typeof AppUNicknameProjectsProjectIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFeedRoute: AppFeedRoute,
  AppUNicknameRoute: AppUNicknameRoute,
  AppUNicknameProjectsProjectIdRoute: AppUNicknameProjectsProjectIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface GuestRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestRegisterRoute: typeof GuestRegisterRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestRegisterRoute: GuestRegisterRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
